// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using trabajo_finall.Data;

#nullable disable

namespace trabajo_finall.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129212149_AddingModels")]
    partial class AddingModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("trabajo_finall.Models.Producto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("nombre")
                        .HasMaxLength(100)
                        .HasColumnType("integer");

                    b.Property<decimal>("precio")
                        .HasColumnType("numeric");

                    b.Property<int>("stock")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("trabajo_finall.Models.Venta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("fecha")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("total")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
